version: '3.8'

services:
  payment-backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - REQUEST_EXPIRY_SECONDS=60
      - CLEANUP_INTERVAL_SECONDS=30
      - CORS_ORIGIN=*
    restart: unless-stopped