AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NFC Wallet Payment Request API

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Environment:
      Variables:
        TABLE_NAME: !Ref PaymentRequestsTable
        TTL_SECONDS: 60

Resources:
  # Lambda Function
  PaymentRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/index.handler
      Events:
        CreateRequest:
          Type: Api
          Properties:
            Path: /payment-requests
            Method: POST
        GetRequest:
          Type: Api
          Properties:
            Path: /payment-requests/{id}
            Method: GET
        CompleteRequest:
          Type: Api
          Properties:
            Path: /payment-requests/{id}/complete
            Method: PUT
        ListRequests:
          Type: Api
          Properties:
            Path: /payment-requests
            Method: GET
        Options:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: OPTIONS
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PaymentRequestsTable

  # DynamoDB Table
  PaymentRequestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: requestId
          AttributeType: S
      KeySchema:
        - AttributeName: requestId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt PaymentRequestFunction.Arn